# web界面设置
server:
  web_listen: "0.0.0.0:8080"

# 解密程序和配置参数设置
wrapper:
  path: "./wrapper"
  state_file: "manager.json"
  # 自动重启进程的日志关键词监控，可以监控多个关键词
  restart_patterns:
    - "KDCanProcessCKC"
    #- "新关键词"

# 账号设置,(wrapper)管理器此处的(ip:端口)对应下载器的(ip:端口)
# 如 us 区域开了3个线程, 填入下方的参数即，解密时就可进行3个线程的负载均衡
# 注意：负载均衡下 m3u8 获取不到，需要下载满血的，请在下载器直接填入各个进程的 解密端口 和 m3u8端口。
cn:
  decrypt-m3u8-port: "127.0.0.1:7778"
  get-m3u8-port: "127.0.0.1:7779"
  
us:
  decrypt-m3u8-port: "127.0.0.1:8888"
  get-m3u8-port: "127.0.0.1:8889"

jp:
  decrypt-m3u8-port: "127.0.0.1:9998"
  get-m3u8-port: "127.0.0.1:9999"
